import type { Lang } from './i18n';

/** 2020年代版だけで使う文言。5言語すべて用意しています。 */
type Copy = {
  heroKicker: string; heroLead: string; scroll: string;
  quote: string; quoteBy: string;
  ch1: string; ch1Head: string; ch1Cap: string;
  ch2: string; ch2Head: string; ch2Note: string; ch2More: string;
  factsHead: string; fItems: string; fAreas: string; fMakers: string; fHours: string;
  ch3: string; ch3Head: string; ch3Body: string; ch3Btn: string;
  ch4: string; ch4Head: string; ch4Body: string; ch4Cap: string; ch4Btn: string;
  ctaHead: string; ctaBody: string; ctaBtn: string; ctaTel: string;
  newsHead: string; newsMore: string;
  soldout: string; yen: string;
};

export const MC: Record<Lang, Copy> = {
  jp: {
    heroKicker: 'LIQUOR SHOP SUMURA — UBE, YAMAGUCHI',
    heroLead: 'フランス銘醸ワインを、山口・宇部から。',
    scroll: 'SCROLL',
    quote: '一本のワインは、土地の歴史と、造り手の手仕事と、瓶の中で過ぎた歳月の結晶です。',
    quoteBy: '店主',
    ch1: '01 — 店について',
    ch1Head: '選ぶ、という仕事。',
    ch1Cap: '山口県宇部市の店舗',
    ch2: '02 — 品揃え',
    ch2Head: 'いま、店にあるもの。',
    ch2Note: '在庫は日々動きます。掲載はごく一部です。',
    ch2More: 'すべての商品を見る',
    factsHead: '03 — 数字',
    fItems: '掲載本数', fAreas: '産　地', fMakers: '生産者', fHours: '営業時間',
    ch3: '04 — 非公開の一角',
    ch3Head: '表に出していない一本を。',
    ch3Body: 'ごく少量の入荷、生産者から直接届いた限定品、長く寝かせた古酒。web に載せていない在庫は、この扉の先でご案内しています。',
    ch3Btn: '非公開在庫へ',
    ch4: '05 — これまで',
    ch4Head: '長く、同じ場所で。',
    ch4Body: '1998年にネットショップを開くまで、弊店のウェブサイトは存在しておりませんでした。大変長い間、皆様方にお世話になっております。',
    ch4Cap: '昭和30年頃の様子',
    ch4Btn: '昔日を見る',
    ctaHead: 'お探しの一本がありましたら。',
    ctaBody: '産地・生産者・年代・ご予算をお聞かせいただければ、ご案内できるものをお伝えします。贈りもののご相談も承ります。',
    ctaBtn: 'お問い合わせ',
    ctaTel: 'お電話でも承ります',
    newsHead: 'お知らせ',
    newsMore: 'お知らせ一覧',
    soldout: '在庫切れ', yen: '',
  },
  en: {
    heroKicker: 'LIQUOR SHOP SUMURA — UBE, YAMAGUCHI',
    heroLead: 'Fine French wines, from Ube in Yamaguchi.',
    scroll: 'SCROLL',
    quote: 'A bottle of wine is the crystallisation of a land’s history, a maker’s craft, and the years that passed inside the glass.',
    quoteBy: 'The owner',
    ch1: '01 — The shop',
    ch1Head: 'Choosing is the work.',
    ch1Cap: 'Our shop in Ube, Yamaguchi',
    ch2: '02 — Selection',
    ch2Head: 'What is on the shelves today.',
    ch2Note: 'Stock moves daily. What you see here is only a fraction.',
    ch2More: 'See the whole list',
    factsHead: '03 — In numbers',
    fItems: 'BOTTLES LISTED', fAreas: 'REGIONS', fMakers: 'PRODUCERS', fHours: 'OPENING HOURS',
    ch3: '04 — The private room',
    ch3Head: 'The bottles we do not put on display.',
    ch3Body: 'Wines that arrived in too few bottles to list, limited cuvées sent to us directly by the growers, back vintages we have cellared for years. What is not on the web is behind this door.',
    ch3Btn: 'Enter the private cellar',
    ch4: '05 — Our history',
    ch4Head: 'A long time in the same place.',
    ch4Body: 'Until we opened our online shop in 1998, this shop had no website at all. We are grateful for the many years of your custom.',
    ch4Cap: 'The shop around 1955',
    ch4Btn: 'See the old days',
    ctaHead: 'Looking for a particular bottle?',
    ctaBody: 'Tell us the region, the grower, the period and the budget you have in mind, and we will tell you what we can offer. We are glad to advise on gifts as well.',
    ctaBtn: 'Get in touch',
    ctaTel: 'Or simply call us',
    newsHead: 'News',
    newsMore: 'All news',
    soldout: 'Sold out', yen: '',
  },
  fr: {
    heroKicker: 'LIQUOR SHOP SUMURA — UBE, YAMAGUCHI',
    heroLead: 'Les grands vins de France, depuis Ube au Yamaguchi.',
    scroll: 'SCROLL',
    quote: 'Une bouteille de vin est la cristallisation de l’histoire d’une terre, du savoir-faire d’un vigneron et des années passées dans le verre.',
    quoteBy: 'Le propriétaire',
    ch1: '01 — La maison',
    ch1Head: 'Choisir, voilà notre métier.',
    ch1Cap: 'Notre boutique à Ube, Yamaguchi',
    ch2: '02 — La sélection',
    ch2Head: 'Ce qui est en rayon aujourd’hui.',
    ch2Note: 'Le stock bouge chaque jour. Ceci n’en est qu’une petite partie.',
    ch2More: 'Voir toute la liste',
    factsHead: '03 — En chiffres',
    fItems: 'BOUTEILLES', fAreas: 'RÉGIONS', fMakers: 'PRODUCTEURS', fHours: 'HORAIRES',
    ch3: '04 — Le cabinet privé',
    ch3Head: 'Les flacons que nous ne mettons pas en vitrine.',
    ch3Body: 'Vins arrivés en trop peu de bouteilles, cuvées limitées reçues directement des vignerons, vieux millésimes gardés ici depuis des années. Ce qui n’est pas en ligne se trouve derrière cette porte.',
    ch3Btn: 'Entrer dans la cave privée',
    ch4: '05 — Notre histoire',
    ch4Head: 'Longtemps, au même endroit.',
    ch4Body: 'Jusqu’à l’ouverture de notre boutique en ligne en 1998, cette maison n’avait aucun site internet. Merci pour toutes ces années de fidélité.',
    ch4Cap: 'La boutique vers 1955',
    ch4Btn: 'Voir le temps jadis',
    ctaHead: 'Vous cherchez une bouteille précise ?',
    ctaBody: 'Indiquez-nous la région, le domaine, la période et le budget souhaités : nous vous dirons ce que nous pouvons proposer. Nous conseillons aussi volontiers pour un cadeau.',
    ctaBtn: 'Nous écrire',
    ctaTel: 'Ou appelez-nous',
    newsHead: 'Actualités',
    newsMore: 'Toutes les actualités',
    soldout: 'Épuisé', yen: '',
  },
  zh: {
    heroKicker: 'LIQUOR SHOP SUMURA — 山口・宇部',
    heroLead: '自山口宇部，奉上法国名庄葡萄酒。',
    scroll: 'SCROLL',
    quote: '一瓶葡萄酒，是土地的历史、酿造者的手艺与瓶中岁月的结晶。',
    quoteBy: '店主',
    ch1: '01 — 关于本店',
    ch1Head: '所谓选酒，即是本职。',
    ch1Cap: '位于山口县宇部市的店铺',
    ch2: '02 — 品项',
    ch2Head: '此刻店中所有。',
    ch2Note: '库存每日变动，此处所列仅为一小部分。',
    ch2More: '查看全部商品',
    factsHead: '03 — 数字',
    fItems: '在售瓶数', fAreas: '产　区', fMakers: '生产者', fHours: '营业时间',
    ch3: '04 — 非公开的一隅',
    ch3Head: '未曾陈列的那一瓶。',
    ch3Body: '到货极少而未上架的酒款、由生产者直接寄达的限量特酿、长年窖藏的旧年份。未在网络公开的库存，尽在此门之后。',
    ch3Btn: '前往非公开库存',
    ch4: '05 — 至今为止',
    ch4Head: '长久地，在同一处。',
    ch4Body: '直至1998年开设网店之前，本店并无网站。长久以来承蒙各位关照，不胜感激。',
    ch4Cap: '昭和30年（1955年）前后的样子',
    ch4Btn: '一览昔日',
    ctaHead: '若有想寻的一瓶。',
    ctaBody: '请告知产区、生产者、年份与预算，我们将奉上此刻可供选择的建议。礼品相关亦欢迎咨询。',
    ctaBtn: '联系我们',
    ctaTel: '亦可致电',
    newsHead: '最新消息',
    newsMore: '消息一览',
    soldout: '售罄', yen: '',
  },
  ko: {
    heroKicker: 'LIQUOR SHOP SUMURA — 야마구치・우베',
    heroLead: '야마구치 우베에서 전하는 프랑스 명양조 와인.',
    scroll: 'SCROLL',
    quote: '한 병의 와인은 땅의 역사와 만드는 이의 손길, 그리고 병 속에서 흐른 세월의 결정입니다.',
    quoteBy: '점주',
    ch1: '01 — 가게에 대하여',
    ch1Head: '고르는 일, 그것이 저희의 일입니다.',
    ch1Cap: '야마구치현 우베시의 점포',
    ch2: '02 — 취급 품목',
    ch2Head: '지금 가게에 있는 것.',
    ch2Note: '재고는 매일 움직입니다. 여기 실린 것은 극히 일부입니다.',
    ch2More: '전체 상품 보기',
    factsHead: '03 — 숫자로',
    fItems: '게재 병수', fAreas: '산　지', fMakers: '생산자', fHours: '영업시간',
    ch3: '04 — 비공개의 한 자리',
    ch3Head: '내놓지 않은 한 병을.',
    ch3Body: '입고 수량이 적어 게재하지 않은 와인, 생산자에게서 직접 받은 한정 퀴베, 오래 눕혀 둔 백빈티지. 웹에 공개하지 않은 재고는 이 문 너머에 있습니다.',
    ch3Btn: '비공개 재고로',
    ch4: '05 — 지나온 길',
    ch4Head: '오랫동안, 같은 자리에서.',
    ch4Body: '1998년에 온라인 숍을 열기 전까지 저희 가게에는 웹사이트가 없었습니다. 오랜 세월 보살펴 주셔서 감사합니다.',
    ch4Cap: '1955년경의 모습',
    ch4Btn: '옛날을 보기',
    ctaHead: '찾으시는 한 병이 있으시다면.',
    ctaBody: '산지・생산자・연대・예산을 알려 주시면 지금 안내 가능한 것을 전해 드립니다. 선물 상담도 환영합니다.',
    ctaBtn: '문의하기',
    ctaTel: '전화로도 받습니다',
    newsHead: '소식',
    newsMore: '소식 전체',
    soldout: '품절', yen: '',
  },
};
