import type { Lang } from './i18n';

/** 2020年代版だけで使う文言。5言語すべて用意しています。 */
type Copy = {
  heroKicker: string; heroLead: string; scroll: string;
  quote: string; quoteBy: string;
  ch1: string; ch1Head: string; ch1Cap: string;
  ch2: string; ch2Head: string; ch2Note: string; ch2More: string;
  factsHead: string; fItems: string; fAreas: string; fMakers: string;
  ch3: string; ch3Head: string; ch3Body: string; ch3Btn: string;
  ch4: string; ch4Head: string; ch4Body: string; ch4Cap: string; ch4Btn: string;
  ctaHead: string; ctaBody: string; ctaBtn: string; ctaTel: string;
  newsHead: string; newsMore: string;
  soldout: string; yen: string;
  capRouget: string; capRoch: string; capGillet: string;
  gallery: string; galleryHead: string;
};

export const MC: Record<Lang, Copy> = {
  jp: {
    heroKicker: 'LIQUOR SHOP SUMURA — UBE, YAMAGUCHI',
    heroLead: 'フランス銘醸ワインを、山口・宇部からお届けしております。',
    scroll: 'SCROLL',
    quote: '一本のワインは、土地の歴史と、造り手の手仕事と、瓶の中で過ぎた歳月の結晶でございます。',
    quoteBy: '店主',
    ch1: '01 ── 私どもについて',
    ch1Head: 'ワインを選ぶという、私どもの仕事。',
    ch1Cap: '山口県宇部市の当店',
    ch2: '02 ── オンラインストア',
    ch2Head: 'お取り扱いのワインから。',
    ch2Note: '在庫は日々動いてまいります。こちらに掲載しておりますのは、そのごく一部でございます。',
    ch2More: 'お取り扱い商品をすべて見る',
    factsHead: '03 ── お取り扱い',
    fItems: '掲載本数', fAreas: '産　地', fMakers: '生産者',
    ch3: '04 ── 非公開のご案内',
    ch3Head: 'お出ししていない一本を。',
    ch3Body: 'ごく少量の入荷、造り手から直接届いた限定品、長く寝かせてまいりました古酒。ウェブに掲載しておりません在庫は、この扉の先でご案内しております。',
    ch3Btn: '非公開のご在庫へ',
    ch4: '05 ── 歩み',
    ch4Head: '長く、同じ場所で。',
    ch4Body: '1998年にネットショップを開くまで、弊店のウェブサイトは存在しておりませんでした。大変長い間、皆様方にお世話になっております。',
    ch4Cap: '昭和30年頃の様子',
    ch4Btn: '昔日をご覧いただく',
    ctaHead: 'お探しの一本がございましたら。',
    ctaBody: '産地・造り手・年代・ご予算をお聞かせいただければ、ご案内できるものをお伝えいたします。贈りもののご相談も承っております。',
    ctaBtn: 'お問い合わせはこちら',
    ctaTel: 'お電話でも承っております',
    newsHead: 'お知らせ',
    newsMore: 'お知らせの一覧へ',
    soldout: '在庫切れ', yen: '',
    capRouget: 'エマニュエル・ルジェ ／ エシェゾー グラン・クリュ', capRoch: 'ジュヴレ・シャンベルタン、ヴォーヌ・ロマネ ／ 届いたばかりの並び', capGillet: 'サヴィニー・レ・ボーヌ ／ 灯りの下で',
    gallery: 'お店の風景', galleryHead: '棚から、いくつかをご紹介いたします。',
  },
  en: {
    heroKicker: 'LIQUOR SHOP SUMURA — UBE, YAMAGUCHI',
    heroLead: 'Fine French wines, from Ube in Yamaguchi.',
    scroll: 'SCROLL',
    quote: 'A bottle of wine is the crystallisation of a land’s history, a maker’s craft, and the years that passed inside the glass.',
    quoteBy: 'The owner',
    ch1: '01 ── About us',
    ch1Head: 'Choosing the bottle is the work.',
    ch1Cap: 'Our shop in Ube, Yamaguchi',
    ch2: '02 ── Online store',
    ch2Head: 'From the wines we carry.',
    ch2Note: 'Stock moves daily. What appears here is only a small part of it.',
    ch2More: 'See the whole list',
    factsHead: '03 ── What we carry',
    fItems: 'BOTTLES LISTED', fAreas: 'REGIONS', fMakers: 'PRODUCERS',
    ch3: '04 ── By introduction',
    ch3Head: 'The bottles we do not put on display.',
    ch3Body: 'Wines that arrived in too few bottles to list, limited cuvées sent to us directly by the growers, back vintages we have cellared for years. What is not on the web is behind this door.',
    ch3Btn: 'Enter the private cellar',
    ch4: '05 ── Our history',
    ch4Head: 'A long time in the same place.',
    ch4Body: 'Until we opened our online shop in 1998, this shop had no website at all. We are grateful for the many years of your custom.',
    ch4Cap: 'The shop around 1955',
    ch4Btn: 'See the old days',
    ctaHead: 'Looking for a particular bottle?',
    ctaBody: 'Tell us the region, the grower, the period and the budget you have in mind, and we will tell you what we can offer. We are glad to advise on gifts as well.',
    ctaBtn: 'Get in touch',
    ctaTel: 'Or simply call us',
    newsHead: 'News',
    newsMore: 'All news',
    soldout: 'Sold out', yen: '',
    capRouget: 'Emmanuel Rouget / Échézeaux Grand Cru', capRoch: 'Gevrey-Chambertin and Vosne-Romanée, just arrived', capGillet: 'Savigny-lès-Beaune, under the lamp',
    gallery: 'The shop', galleryHead: 'A few from the shelves.',
  },
  fr: {
    heroKicker: 'LIQUOR SHOP SUMURA — UBE, YAMAGUCHI',
    heroLead: 'Les grands vins de France, depuis Ube au Yamaguchi.',
    scroll: 'SCROLL',
    quote: 'Une bouteille de vin est la cristallisation de l’histoire d’une terre, du savoir-faire d’un vigneron et des années passées dans le verre.',
    quoteBy: 'Le propriétaire',
    ch1: '01 ── À notre sujet',
    ch1Head: 'Choisir la bouteille, voilà notre métier.',
    ch1Cap: 'Notre boutique à Ube, Yamaguchi',
    ch2: '02 ── Boutique en ligne',
    ch2Head: 'Parmi les vins que nous proposons.',
    ch2Note: 'Le stock bouge chaque jour. Ce que vous voyez ici n’en est qu’une petite part.',
    ch2More: 'Voir toute la liste',
    factsHead: '03 ── Ce que nous proposons',
    fItems: 'BOUTEILLES', fAreas: 'RÉGIONS', fMakers: 'PRODUCTEURS',
    ch3: '04 ── Sur présentation',
    ch3Head: 'Les flacons que nous ne mettons pas en vitrine.',
    ch3Body: 'Vins arrivés en trop peu de bouteilles, cuvées limitées reçues directement des vignerons, vieux millésimes gardés ici depuis des années. Ce qui n’est pas en ligne se trouve derrière cette porte.',
    ch3Btn: 'Entrer dans la cave privée',
    ch4: '05 ── Notre histoire',
    ch4Head: 'Longtemps, au même endroit.',
    ch4Body: 'Jusqu’à l’ouverture de notre boutique en ligne en 1998, cette maison n’avait aucun site internet. Merci pour toutes ces années de fidélité.',
    ch4Cap: 'La boutique vers 1955',
    ch4Btn: 'Voir le temps jadis',
    ctaHead: 'Vous cherchez une bouteille précise ?',
    ctaBody: 'Indiquez-nous la région, le domaine, la période et le budget souhaités : nous vous dirons ce que nous pouvons proposer. Nous conseillons aussi volontiers pour un cadeau.',
    ctaBtn: 'Nous écrire',
    ctaTel: 'Ou appelez-nous',
    newsHead: 'Actualités',
    newsMore: 'Toutes les actualités',
    soldout: 'Épuisé', yen: '',
    capRouget: 'Emmanuel Rouget / Échézeaux Grand Cru', capRoch: 'Gevrey-Chambertin et Vosne-Romanée, à peine arrivés', capGillet: 'Savigny-lès-Beaune, sous la lampe',
    gallery: 'La maison', galleryHead: 'Quelques flacons des rayons.',
  },
  zh: {
    heroKicker: 'LIQUOR SHOP SUMURA — 山口・宇部',
    heroLead: '自山口宇部，奉上法国名庄葡萄酒。',
    scroll: 'SCROLL',
    quote: '一瓶葡萄酒，是土地的历史、酿造者的手艺与瓶中岁月的结晶。',
    quoteBy: '店主',
    ch1: '01 ── 关于本店',
    ch1Head: '选酒，即是本店的本职。',
    ch1Cap: '位于山口县宇部市的店铺',
    ch2: '02 ── 网上商店',
    ch2Head: '自本店经手的葡萄酒中。',
    ch2Note: '库存每日流动。此处所列，仅为其中极小的一部分。',
    ch2More: '查看全部商品',
    factsHead: '03 ── 经手品项',
    fItems: '在售瓶数', fAreas: '产　区', fMakers: '生产者',
    ch3: '04 ── 非公开的介绍',
    ch3Head: '未曾陈列的那一瓶。',
    ch3Body: '到货极少而未上架的酒款、由生产者直接寄达的限量特酿、长年窖藏的旧年份。未在网络公开的库存，尽在此门之后。',
    ch3Btn: '前往非公开库存',
    ch4: '05 ── 本店的历程',
    ch4Head: '长久地，在同一处。',
    ch4Body: '直至1998年开设网店之前，本店并无网站。长久以来承蒙各位关照，不胜感激。',
    ch4Cap: '昭和30年（1955年）前后的样子',
    ch4Btn: '一览昔日',
    ctaHead: '若有想寻的一瓶。',
    ctaBody: '请告知产区、生产者、年份与预算，我们将奉上此刻可供选择的建议。礼品相关亦欢迎咨询。',
    ctaBtn: '联系我们',
    ctaTel: '亦可致电',
    newsHead: '最新消息',
    newsMore: '消息一览',
    soldout: '售罄', yen: '',
    capRouget: '埃玛纽埃尔·卢梭 ／ 埃雪索 特级园', capRoch: '热夫雷·香贝丹与沃恩·罗曼尼 ／ 刚到货的一列', capGillet: '萨维尼·莱·博讷 ／ 灯下',
    gallery: '店内一景', galleryHead: '取自架上的数瓶。',
  },
  ko: {
    heroKicker: 'LIQUOR SHOP SUMURA — 야마구치・우베',
    heroLead: '야마구치 우베에서 전하는 프랑스 명양조 와인.',
    scroll: 'SCROLL',
    quote: '한 병의 와인은 땅의 역사와 만드는 이의 손길, 그리고 병 속에서 흐른 세월의 결정입니다.',
    quoteBy: '점주',
    ch1: '01 ── 저희에 대하여',
    ch1Head: '와인을 고르는 일, 그것이 저희의 일입니다.',
    ch1Cap: '야마구치현 우베시의 점포',
    ch2: '02 ── 온라인 스토어',
    ch2Head: '저희가 취급하는 와인 가운데에서.',
    ch2Note: '재고는 매일 움직입니다. 여기에 실린 것은 그중 극히 일부입니다.',
    ch2More: '전체 상품 보기',
    factsHead: '03 ── 취급 품목',
    fItems: '게재 병수', fAreas: '산　지', fMakers: '생산자',
    ch3: '04 ── 소개를 통하여',
    ch3Head: '내놓지 않은 한 병을.',
    ch3Body: '입고 수량이 적어 게재하지 않은 와인, 생산자에게서 직접 받은 한정 퀴베, 오래 눕혀 둔 백빈티지. 웹에 공개하지 않은 재고는 이 문 너머에 있습니다.',
    ch3Btn: '비공개 재고로',
    ch4: '05 ── 걸어온 길',
    ch4Head: '오랫동안, 같은 자리에서.',
    ch4Body: '1998년에 온라인 숍을 열기 전까지 저희 가게에는 웹사이트가 없었습니다. 오랜 세월 보살펴 주셔서 감사합니다.',
    ch4Cap: '1955년경의 모습',
    ch4Btn: '옛날을 보기',
    ctaHead: '찾으시는 한 병이 있으시다면.',
    ctaBody: '산지・생산자・연대・예산을 알려 주시면 지금 안내 가능한 것을 전해 드립니다. 선물 상담도 환영합니다.',
    ctaBtn: '문의하기',
    ctaTel: '전화로도 받습니다',
    newsHead: '소식',
    newsMore: '소식 전체',
    soldout: '품절', yen: '',
    capRouget: '에마뉘엘 루제 / 에셰조 그랑 크뤼', capRoch: '주브레 샹베르탱과 본 로마네 / 막 들어온 줄', capGillet: '사비니 레 본 / 등불 아래',
    gallery: '가게의 풍경', galleryHead: '선반에서 몇 병을.',
  },
};

/** 2010年代・2020年代のブログ見出し（「よもやま日記」は古い時代だけに残します） */
export const BLOG_TITLE: Record<Lang, string> = {
  jp: 'すむら酒店　ブログ',
  en: 'Liquor Shop Sumura — Journal',
  fr: 'Liquor Shop Sumura — Journal',
  zh: 'すむら酒店 博客',
  ko: '스무라 주점 블로그',
};

/** 2010年代・2020年代では略さず正式名称で示します */
export const LEGAL_TITLE: Record<Lang, string> = {
  jp: '特定商取引法に基づく表記',
  en: 'Legal notice (Act on Specified Commercial Transactions)',
  fr: 'Mentions légales (loi sur les transactions commerciales spécifiées)',
  zh: '基于特定商业交易法的表示',
  ko: '특정상거래법에 근거한 표기',
};
